# Generated by Django 3.1.3 on 2020-11-29 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Addresses',
        ),
    ]
