# Generated by Django 3.1.5 on 2021-02-07 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('image', models.TextField()),
                ('title', models.TextField()),
                ('newspaper', models.TextField()),
                ('category', models.TextField()),
                ('date', models.TextField(default=datetime.date(2021, 2, 7))),
            ],
        ),
    ]
