# Generated by Django 3.1.3 on 2021-04-08 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webtoons', '0003_auto_20210324_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daum',
            name='date',
            field=models.TextField(default=datetime.date(2021, 4, 8)),
        ),
        migrations.AlterField(
            model_name='naver',
            name='date',
            field=models.TextField(default=datetime.date(2021, 4, 8)),
        ),
    ]
